#!/bin/sh

rm -rf *pdf
rm -rf *tex
rm -rf *aux
rm -rf *Rnw
rm -rf *blg
rm -rf *brf
rm -rf *bbl
rm -rf *log
rm -rf *out
rm -rf *toc
rm -rf lpmvnorm*
rm -rf ltMatrices*

for f in ./R/*~; do
    rm -f $f
done

for f in ./R/*.ps; do
    rm -f $f
done


for f in ./man/*~; do
    rm -f $f
done

for f in ./man/*.ps; do
    rm -f $f
done


for f in ./inst/*~; do
    rm -f $f
done

for f in ./tests/*~; do
    rm -f $f
done

for f in ./tests/*.ps; do
    rm -f $f
done

for f in ./src/*.*o; do
    rm -f $f
done

for f in ./src/*~; do
    rm -f $f
done

for f in *~; do
    rm -f $f
done

find . -name "DEADJOE" -exec rm -f {} \;

find . -name "mvtnormAPI*gz" -exec rm -f {} \;

find . -name "mvtnormAPI.Rcheck" -exec rm -rf {} \;

exit 0
