#!/bin/bash

for f in ./src/*.*o; do
    rm -f $f
done

for f in ./src/*.c; do
    rm -f $f
done

for f in ./src/*~; do
    rm -f $f
done

for f in ./R/*~; do
    rm -f $f
done

for f in ./man/*~; do
    rm -f $f
done

for f in *~; do
    rm -f $f
done

find . -name "DEADJOE" -exec rm -f {} \;

exit 0
